---
# User to be added to docker group.
# By default uses the SSH user (usually ubuntu).
docker_user: "{{ ansible_user | default('ubuntu') }}"

# Official Docker repository key and repo
# (Ubuntu)
docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_keyring_path: "/etc/apt/keyrings/docker.gpg"
docker_repo_filename: "docker"

# Docker packages to install
# docker-compose-plugin gives `docker compose` command.
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
